import {
	FleetVehicle,
	FleetTrip,
	FleetStats,
	FleetTripStats,
	PurchaseOrder,
	FastagTransaction,
	FleetPurchaseStats,
	FleetFastagStats,
	FastagExpenseStats,
	MaintenanceRecord,
	MaintenanceStats,
	RenewalItem,
	TireRecord,
	TireManagementStats,
	RotationLog,
	ComplianceRecord,
	ComplianceManagementStats,
	DriverRecord,
	DriverManagementStats,
} from "../../types/fleet";

// ---------------------------------------------------------------------------
// Tab 1 – Vehicles
// ---------------------------------------------------------------------------
export const dummyVehicles: FleetVehicle[] = [
	{
		id: "vehicle-1",
		vehicleNumber: "MH-12-FR-4592",
		type: "Heavy Truck (12W)",
		modelYear: "Tata Prime 4923 2023",
		capacity: "24,000 Kg",
		assignedDriver: "Rajesh Kumar",
		status: "In Transit",
		regExp: "12 Nov 2025",
		insuranceExp: "28 Jan 2025",
		modelName: ""
	},
	{
		id: "vehicle-2",
		vehicleNumber: "DL-01-AX-1022",
		type: "Refrigerated Van",
		modelYear: "Eicher Pro 6000 2021",
		capacity: "8,500 Kg",
		assignedDriver: "Unassigned",
		status: "Maintenance",
		regExp: "15 Jul 2025",
		insuranceExp: "—",
		modelName: ""
	},
	{
		id: "vehicle-3",
		vehicleNumber: "KA-51-MM-0092",
		type: "LCV",
		modelYear: "Ashok Leyland 2023",
		capacity: "2,500 Kg",
		assignedDriver: "Suresh Murali",
		status: "Available",
		regExp: "15 Jun 2026",
		insuranceExp: "22 Aug 2025",
		modelName: ""
	},
	{
		id: "vehicle-4",
		vehicleNumber: "MH-04-TT-9921",
		type: "HCV",
		modelYear: "BharatBenz 3523R 2020",
		capacity: "35,000 Kg",
		assignedDriver: "Amit Singh",
		status: "Inactive",
		regExp: "09 Mar 2025",
		insuranceExp: "—",
		modelName: ""
	},
	{
		id: "vehicle-5",
		vehicleNumber: "HR-55-QR-3321",
		type: "Heavy Truck",
		modelYear: "Ashok Leyland 2018",
		capacity: "18,500 Kg",
		assignedDriver: "Decommissioned",
		status: "Inactive", // design shows Inactive (not Decommissioned)
		regExp: "Expired",
		insuranceExp: "Expired",
		modelName: ""
	},
];

// ---------------------------------------------------------------------------
// Vehicle Stats  (Tab 1 cards)
// ---------------------------------------------------------------------------
export const initialVehicleStats: FleetStats = {
	totalVehicles: "482",
	activeTrips: "156",
	maintenance: "3",
};

// ---------------------------------------------------------------------------
// Tab 2 – Trip Management
// ---------------------------------------------------------------------------
export const dummyTrips: FleetTrip[] = [
	{
		id: "trip-1",
		tripId: "TRP-98421",
		vehicle: "MH-12-DE-1024",
		driver: "Rajesh Kumar",
		route: "Mumbai → Pune",
		departure: "Oct 24, 08:30\nETA: 11:45 AM",
		distance: "152 Km",
		status: "Active",
	},
	{
		id: "trip-2",
		tripId: "TRP-98405",
		vehicle: "DL-01-FG-4491",
		driver: "Amit Kumar",
		route: "Delhi → Jaipur",
		departure: "Oct 24, 06:15\nLate: 45m",
		distance: "281 Km",
		status: "Delayed",
	},
	{
		id: "trip-3",
		tripId: "TRP-98450",
		vehicle: "KA-05-MN-2233",
		driver: "Vikram Singh",
		route: "Bangalore → Mysore",
		departure: "Oct 24, 11:00\nScheduled",
		distance: "144 Km",
		status: "Planned",
	},
	{
		id: "trip-4",
		tripId: "TRP-98380",
		vehicle: "TN-07-JK-0055",
		driver: "S. Narayanan",
		route: "Chennai → Madurai",
		departure: "Oct 24, 11:00\nFinished: 34:30 AM",
		distance: "462 Km",
		status: "Completed",
	},
	{
		id: "trip-5",
		tripId: "TRP-98433",
		vehicle: "HR-55-XY-8812",
		driver: "Pritam Maurya",
		route: "Gurgaon → Chandigarh",
		departure: "Oct 24, 09:15\nETA: 01:30 PM",
		distance: "265 Km",
		status: "Active",
	},
];

// ---------------------------------------------------------------------------
// Trip Stats  (Tab 2 cards)
// ---------------------------------------------------------------------------
export const initialTripStats: FleetTripStats = {
	activeVehicles: "482",
	activeTrips: "142",
	delayTrips: "08",
};

// ---------------------------------------------------------------------------
// Tab 3 – Purchase Orders
// ---------------------------------------------------------------------------
export const dummyPurchaseOrders: PurchaseOrder[] = [
	{
		id: 1,
		po: "#Po-2023-0941",
		vendor: "Michelin Fleet Solutions",
		tag: "Tires",
		amount: "$12,450.00",
		status: "Ordered",
		statusColor: "bg-[#054B94]/13 text-primary border border-blue-100",
		date: "Oct 24, 2023",
	},
	{
		id: 2,
		po: "#Po-2023-0942",
		vendor: "Fleet Fuel International",
		tag: null,
		amount: "$45,000.00",
		status: "Received",
		statusColor: "bg-[#054B94]/13 text-primary border border-emerald-100",
		date: "Oct 21, 2023",
	},
	{
		id: 3,
		po: "#Po-2023-0943",
		vendor: "Auto-Part Distributors",
		tag: "SPARE PARTS",
		amount: "$2,100.00",
		status: "Draft",
		statusColor: "bg-[#FFD7D7] text-[#880000] border border-red-100",
		date: "TBD",
	},
	{
		id: 4,
		po: "#Po-2023-0944",
		vendor: "Precision Logistics Tires",
		tag: null,
		amount: "$8,200.00",
		status: "Pending Approval",
		statusColor: "bg-[#8760FF]/13 text-[#2F0D83] border border-purple-100",
		date: "Nov 02, 2023",
	},
	{
		id: 5,
		po: "#Po-2023-0945",
		vendor: "Global Fuel & Gas Co.",
		tag: "Fuel Cards",
		amount: "$38,000.00",
		status: "Ordered",
		statusColor: "bg-[#054B94]/13 text-primary border border-blue-100",
		date: "Oct 28, 2023",
	},
	{
		id: 6,
		po: "#Po-2023-0946",
		vendor: "Brake Master Ind.",
		tag: "SPARE PARTS",
		amount: "$4,520.00",
		status: "Received",
		statusColor: "bg-[#054B94]/13 text-primary border border-emerald-100",
		date: "Oct 19, 2023",
	},
	{
		id: 7,
		po: "#Po-2023-0947",
		vendor: "Michelin Fleet Solution",
		tag: "Tires",
		amount: "$15,700.00",
		status: "Pending Approval",
		statusColor: "bg-[#8760FF]/13 text-[#2F0D83] border border-purple-100",
		date: "Nov 05, 2023",
	},
	{
		id: 8,
		po: "#Po-2023-0948",
		vendor: "Transmission Specialists",
		tag: "SPARE PARTS",
		amount: "$9,800.00",
		status: "Received",
		statusColor: "bg-[#054B94]/13 text-primary border border-emerald-100",
		date: "Oct 30, 2023",
	},
];

// ---------------------------------------------------------------------------
// Purchase Stats  (Tab 3 cards) — values from design
// ---------------------------------------------------------------------------
export const initialPurchaseStats: FleetPurchaseStats = {
	totalPoSpend: { value: "482", badge: "+13%" }, // design shows +13%
	onTimeDeliveryRate: { value: "14", badge: "-12%" },
	activeVendors: { value: "42", badge: "+4%" },
	pendingDeliveries: { value: "3", badge: "-2%" },
};

// ---------------------------------------------------------------------------
// Tab 4 – Fastag & Expenses
// ---------------------------------------------------------------------------

// Header card indicators (fastagStats)
export const initialFastagStats: FastagExpenseStats = {
	totalBalance: "₹4,28,450",
	activeWallets: "412",
	lowBalanceAlerts: "5",
};

// Fastag transactions table
export const dummyFastagTransactions: FastagTransaction[] = [
	{
		date: "Oct 24, 08:30",
		vehicle: "MH-12-DE-1024",
		plaza: "Khed-Shivapur, NH-4",
		amount: "- ₹420.00",
		isNegative: true,
		balance: "₹12,450.00",
		isLowBal: false,
	},
	{
		date: "Oct 24, 06:15",
		vehicle: "DL-01-FG-4491",
		plaza: "Tumkur Tollway",
		amount: "- ₹280.00",
		isNegative: true,
		balance: "₹142.00",
		isLowBal: true,
	},
	{
		date: "Oct 24, 11:00",
		vehicle: "KA-05-MN-2233",
		plaza: "Panipat Plaza, NH-1",
		amount: "- ₹560.00",
		isNegative: true,
		balance: "₹8,120.00",
		isLowBal: false,
	},
	{
		date: "Oct 24, 11:00",
		vehicle: "TN-07-JK-0055",
		plaza: "RECHARGE: HDFC- 771",
		amount: "+ ₹10,000.00",
		isNegative: false,
		balance: "₹15,400.00",
		isLowBal: false,
	},
	{
		date: "Oct 24, 09:15",
		vehicle: "HR-55-XY-8812",
		plaza: "Vashi Toll Plaza",
		amount: "- ₹100.00",
		isNegative: true,
		balance: "₹4,200.00",
		isLowBal: false,
	},
	{
		date: "Oct 24, 11:00",
		vehicle: "TN-02-RR-0055",
		plaza: "Chennasamudram Plaza",
		amount: "- ₹210.00",
		isNegative: true,
		balance: "₹21,300.00",
		isLowBal: false,
	},
	{
		date: "Oct 24, 07:02",
		vehicle: "GJ-05-UU-5544",
		plaza: "Bharuch Toll, NH-8",
		amount: "- ₹350.00",
		isNegative: true,
		balance: "₹9,800.00",
		isLowBal: false,
	},
];

// Fastag dashboard metric cards
export const initialFastagDashboardStats: FleetFastagStats = {
	totalBalance: "₹4,28,450",
	monthlySpend: "₹12,40,900",
	additionalExpenses: "₹6,15,000",
	totalBalanceTrend: "⬇ 12%",
	monthlySpendTrend: "⬆ 4.2%",
	additionalExpensesTrend: "⬆ 12%",
	lowBalanceVehicles: ["MH-12-DE-9944", "KA-01-JK-2210", "TS-09-ER-3342"],
};

// ---------------------------------------------------------------------------
// Tab 5 – Maintenance
// ---------------------------------------------------------------------------

export const dummyMaintenanceRecords: MaintenanceRecord[] = [
	{
		id: "mnt-1",
		vehicleNumber: "MH-12-DT-8842",
		serviceType: "Engine Overhaul",
		serviceDate: "Oct 24, 2023",
		mileage: "142,500 Km",
		serviceCenter: "Apex Motors Central",
		status: "Overdue",
		cost: "$1,450.00",
	},
	{
		id: "mnt-2",
		vehicleNumber: "KA-01-MJ-2201",
		serviceType: "Brake Inspection",
		serviceDate: "Nov 02, 2023",
		mileage: "88, 240 Km",
		serviceCenter: "Reliable Fleet Hub",
		status: "In Progress",
		cost: "$320.00",
	},
	{
		id: "mnt-3",
		vehicleNumber: "Hr-26-CP-1159",
		serviceType: "Tire Rotation",
		serviceDate: "Nov 15, 2023",
		mileage: "12,100 Km",
		serviceCenter: "Main Street Garage",
		status: "Scheduled",
		cost: "$85.00",
	},
	{
		id: "mnt-4",
		vehicleNumber: "DL-01-AB-0001",
		serviceType: "Oil Chnage",
		serviceDate: "Nov 15, 2023",
		mileage: "45,000 Km",
		serviceCenter: "City Service Point",
		status: "Scheduled",
		cost: "$110.00",
	},
	{
		id: "mnt-5",
		vehicleNumber: "TN-07-JK-4432",
		serviceType: "AC Servicing",
		serviceDate: "Nov 20, 2023",
		mileage: "67,800 Km",
		serviceCenter: "Frost-Air Tech",
		status: "Scheduled",
		cost: "$245.00",
	},
	{
		id: "mnt-6",
		vehicleNumber: "MH-04-BJ-9912",
		serviceType: "Suspension Check",
		serviceDate: "Nov 22, 2023",
		mileage: "98,300 Km",
		serviceCenter: "AutoCare Express",
		status: "Scheduled",
		cost: "$390.00",
	},
	{
		id: "mnt-7",
		vehicleNumber: "GJ-05-KL-7821",
		serviceType: "Battery Replacement",
		serviceDate: "Nov 25, 2023",
		mileage: "55,120 Km",
		serviceCenter: "PowerDrive Service",
		status: "In Progress",
		cost: "$520.00",
	},
	{
		id: "mnt-8",
		vehicleNumber: "RJ-14-GH-3301",
		serviceType: "Clutch Repair",
		serviceDate: "Nov 28, 2023",
		mileage: "1,10,450 Km",
		serviceCenter: "Rajasthan Motors Hub",
		status: "Overdue",
		cost: "$875.00",
	},
	{
		id: "mnt-9",
		vehicleNumber: "UP-32-CD-5544",
		serviceType: "Exhaust System Service",
		serviceDate: "Dec 01, 2023",
		mileage: "78,900 Km",
		serviceCenter: "Northern Fleet Works",
		status: "Scheduled",
		cost: "$310.00",
	},
	{
		id: "mnt-10",
		vehicleNumber: "WB-06-EF-2298",
		serviceType: "Transmission Flush",
		serviceDate: "Dec 05, 2023",
		mileage: "1,23,000 Km",
		serviceCenter: "East India Auto Service",
		status: "Scheduled",
		cost: "$460.00",
	},
];

export const initialMaintenanceStats: MaintenanceStats = {
	underMaintenance: "24",
	underMaintenanceBadge: "-2%",
	overdueServices: "07",
	overdueServicesBadge: "+12%",
};

export const dummyRenewalItems: RenewalItem[] = [
	{
		id: "ren-1",
		type: "insurance",
		title: "Insurance: Ka-01-MJ",
		vehicle: "Ka-01-MJ",
		expiresIn: "Expires in 4 days",
		actionLabel: "Renew",
		isUrgent: false,
	},
	{
		id: "ren-2",
		type: "pollution",
		title: "Pollution Certificate",
		vehicle: "MH-12-DT",
		expiresIn: "MH-12-DT Expires Today",
		actionLabel: "Action",
		isUrgent: true,
	},
];

// ---------------------------------------------------------------------------
// Tab 6 – Tire Management
// ---------------------------------------------------------------------------

export const initialTireStats: TireManagementStats = {
	replacementDue: { value: "42", subtext: "Tires above 80% wear" },
	monitorStatus: { value: "128", subtext: "Requires inspection in < 2k km" },
	avgLifespan: { value: "58.4k", subtext: "Kilometers per tire brand" },
};

export const dummyTireRecords: TireRecord[] = [
	{
		id: "tire-1",
		vehicle: "MH-12-AX-8842",
		position: "Front Right",
		brand: "Michelin X Multi",
		installDate: "Oct 14 2023",
		mileage: "42,340",
		dueIn: "1,200 km",
		status: "REPLACE",
		isOverdue: true,
	},
	{
		id: "tire-2",
		vehicle: "KA-05-GT-1192",
		position: "Rear Inner Left",
		brand: "Bridgestone M729",
		installDate: "Jan 02 2024",
		mileage: "28,100",
		dueIn: "14,900 Km",
		status: "MONITOR",
		isOverdue: false,
	},
	{
		id: "tire-3",
		vehicle: "DL-01-CR-5520",
		position: "Front Left",
		brand: "Apollo EnduRace",
		installDate: "May 18 2024",
		mileage: "12,450",
		dueIn: "32,550 Km",
		status: "GOOD",
		isOverdue: false,
	},
	{
		id: "tire-4",
		vehicle: "MH-04-BJ-9912",
		position: "Rear outer right",
		brand: "Michelin X Multi",
		installDate: "Sep 11 2023",
		mileage: "51,000",
		dueIn: "Past Due",
		status: "REPLACE",
		isOverdue: true,
	},
	{
		id: "tire-5",
		vehicle: "GL-02-ZZ-0043",
		position: "Front Right",
		brand: "JK Tyre Jetstell",
		installDate: "Feb 22 2024",
		mileage: "22,100",
		dueIn: "17,900 Km",
		status: "MONITOR",
		isOverdue: false,
	},
	{
		id: "tire-6",
		vehicle: "KA-05-GT-1192",
		position: "Rear Inner Left",
		brand: "Bridgestone M729",
		installDate: "Jan 02 2024",
		mileage: "28,100",
		dueIn: "14,900 Km",
		status: "MONITOR",
		isOverdue: false,
	},
	{
		id: "tire-7",
		vehicle: "DL-01-CR-5520",
		position: "Front Left",
		brand: "Apollo EnduRace",
		installDate: "May 18 2024",
		mileage: "12,450",
		dueIn: "32,550 Km",
		status: "GOOD",
		isOverdue: false,
	},
	{
		id: "tire-8",
		vehicle: "TN-09-AB-4321",
		position: "Rear Outer Right",
		brand: "Ceat Shonar Gold",
		installDate: "Mar 10 2024",
		mileage: "18,600",
		dueIn: "26,400 Km",
		status: "GOOD",
		isOverdue: false,
	},
	{
		id: "tire-9",
		vehicle: "HR-26-XY-8812",
		position: "Front Left",
		brand: "Michelin X Multi",
		installDate: "Aug 05 2023",
		mileage: "47,200",
		dueIn: "2,800 km",
		status: "REPLACE",
		isOverdue: true,
	},
	{
		id: "tire-10",
		vehicle: "WB-06-LL-0098",
		position: "Rear Inner Right",
		brand: "Bridgestone M729",
		installDate: "Nov 20 2023",
		mileage: "31,450",
		dueIn: "11,550 Km",
		status: "MONITOR",
		isOverdue: false,
	},
	{
		id: "tire-11",
		vehicle: "MH-01-EE-3210",
		position: "Front Right",
		brand: "Apollo EnduRace",
		installDate: "Jun 14 2024",
		mileage: "8,300",
		dueIn: "36,700 Km",
		status: "GOOD",
		isOverdue: false,
	},
	{
		id: "tire-12",
		vehicle: "RJ-14-GH-3301",
		position: "Rear Outer Left",
		brand: "JK Tyre Jetstell",
		installDate: "Dec 01 2023",
		mileage: "39,800",
		dueIn: "Past Due",
		status: "REPLACE",
		isOverdue: true,
	},
	{
		id: "tire-13",
		vehicle: "GJ-05-KL-7821",
		position: "Front Left",
		brand: "Ceat Shonar Gold",
		installDate: "Feb 18 2024",
		mileage: "24,150",
		dueIn: "20,850 Km",
		status: "MONITOR",
		isOverdue: false,
	},
	{
		id: "tire-14",
		vehicle: "DL-12-QQ-8821",
		position: "Rear Inner Left",
		brand: "Bridgestone M729",
		installDate: "Oct 30 2023",
		mileage: "36,720",
		dueIn: "6,280 Km",
		status: "MONITOR",
		isOverdue: false,
	},
];

export const dummyRotationLogs: RotationLog[] = [
	{
		id: "rot-1",
		dateStr: "Today",
		timeStr: "09:45 AM",
		vehicle: "MH-12-AX-8842",
		description:
			"Full 6-tire rotation completed at Workshop A. Tread depth verified.",
		type: "rotation",
	},
	{
		id: "rot-2",
		dateStr: "24 Oct",
		timeStr: "02:20 PM",
		vehicle: "KA-05-GT-1192",
		description: "Alignment adjustment and balancing for front axle tires.",
		type: "alignment",
	},
	{
		id: "rot-3",
		dateStr: "23 Oct",
		timeStr: "11:10 AM",
		vehicle: "DL-01-CR-5520",
		description: "Emergency roadside repair: Front Left puncture plug.",
		type: "repair",
	},
	{
		id: "rot-4",
		dateStr: "21 Oct",
		timeStr: "04:30 PM",
		vehicle: "GJ-02-ZZ-0043",
		description: "Cross rotation (X) for rear axle sets.",
		type: "rotation",
	},
];

// ---------------------------------------------------------------------------
// Tab 7 – Document & Compliance
// ---------------------------------------------------------------------------

export const initialComplianceStats: ComplianceManagementStats = {
	criticalAttention: {
		value: "12",
		subtext: "Document Expiring Soon",
		isCritical: true,
	},
	assetsHealth: {
		value: "94.2%",
		subtext: "~ 2.4% vs last month",
		trend: "up",
	},
	pendingRenewal: {
		value: "08",
		subtext: "In - Process application",
	},
};

export const dummyComplianceRecords: ComplianceRecord[] = [
	{
		id: "comp-1",
		vehicle: "MH-12-FG-9082",
		docType: "RC (Registration)",
		expiryDate: "Oct 12, 2024",
		status: "Expired",
		lastUpdated: "2 Days Ago",
		isOverdue: true,
	},
	{
		id: "comp-2",
		vehicle: "KA-01-JK-5541",
		docType: "Fitness Certificate",
		expiryDate: "Dec 05, 2026",
		status: "Expired soon",
		lastUpdated: "14 Days Ago",
		isOverdue: true,
	},
	{
		id: "comp-3",
		vehicle: "DL-04-RS-2233",
		docType: "Insurance Policy",
		expiryDate: "Aug 20, 2024",
		status: "Valid",
		lastUpdated: "Just Now",
		isOverdue: false,
	},
	{
		id: "comp-4",
		vehicle: "HR-26-TY-1109",
		docType: "PUC Certificate",
		expiryDate: "Feb 14, 2024",
		status: "Valid",
		lastUpdated: "05 Days Ago",
		isOverdue: false,
	},
	{
		id: "comp-5",
		vehicle: "TN-10-AB-4321",
		docType: "National Permit",
		expiryDate: "Dec 10, 2023",
		status: "Expired soon",
		lastUpdated: "1 month ago",
		isOverdue: true,
	},
	{
		id: "comp-6",
		vehicle: "WB-02-LL-0098",
		docType: "RC (Registration)",
		expiryDate: "Oct 22, 2028",
		status: "Valid",
		lastUpdated: "6 months ago",
		isOverdue: false,
	},
	{
		id: "comp-7",
		vehicle: "MH-01-EE-3210",
		docType: "Insurance Policy",
		expiryDate: "Nov 30, 2023",
		status: "Expired soon",
		lastUpdated: "3 days ago",
		isOverdue: true,
	},
	{
		id: "comp-8",
		vehicle: "DL-12-QQ-8821",
		docType: "Fitness Certificate",
		expiryDate: "Jan 12, 2024",
		status: "Valid",
		lastUpdated: "10 days ago",
		isOverdue: false,
	},
	{
		id: "comp-9",
		vehicle: "MH-12-FR-4592",
		docType: "National Permit",
		expiryDate: "Mar 15, 2025",
		status: "Valid",
		lastUpdated: "3 days ago",
		isOverdue: false,
	},
	{
		id: "comp-10",
		vehicle: "KA-51-MM-0092",
		docType: "PUC Certificate",
		expiryDate: "Nov 08, 2023",
		status: "Expired",
		lastUpdated: "1 week ago",
		isOverdue: true,
	},
	{
		id: "comp-11",
		vehicle: "GJ-05-KL-7821",
		docType: "Insurance Policy",
		expiryDate: "Apr 20, 2026",
		status: "Valid",
		lastUpdated: "Just Now",
		isOverdue: false,
	},
	{
		id: "comp-12",
		vehicle: "HR-55-QR-3321",
		docType: "RC (Registration)",
		expiryDate: "Jan 01, 2024",
		status: "Expired soon",
		lastUpdated: "2 weeks ago",
		isOverdue: true,
	},
	{
		id: "comp-13",
		vehicle: "UP-32-CD-5544",
		docType: "Fitness Certificate",
		expiryDate: "Jul 30, 2025",
		status: "Valid",
		lastUpdated: "5 days ago",
		isOverdue: false,
	},
	{
		id: "comp-14",
		vehicle: "RJ-14-GH-3301",
		docType: "PUC Certificate",
		expiryDate: "Sep 12, 2023",
		status: "Expired",
		lastUpdated: "1 month ago",
		isOverdue: true,
	},
	{
		id: "comp-15",
		vehicle: "TN-07-JK-4432",
		docType: "National Permit",
		expiryDate: "Feb 28, 2025",
		status: "Valid",
		lastUpdated: "4 days ago",
		isOverdue: false,
	},
	{
		id: "comp-16",
		vehicle: "DL-01-AB-0001",
		docType: "Insurance Policy",
		expiryDate: "Dec 31, 2023",
		status: "Expired soon",
		lastUpdated: "8 days ago",
		isOverdue: true,
	},
];

// ---------------------------------------------------------------------------
// Tab 8 – Driver Directory
// ---------------------------------------------------------------------------

export const initialDriverStats: DriverManagementStats = {
	licenseExpiries: {
		value: "12",
		subtext: "↑ +4 from last month",
		isAlert: true,
	},
	activeDrivers: {
		value: "158",
		subtext: "140 currently assigned",
	},
	avgSafetyRating: {
		value: "4.8",
		subtext: "Stable vs last week",
	},
};

export const dummyDriverRecords: DriverRecord[] = [
	{
		id: "drv-1",
		driverId: "DRV-9021",
		name: "Johnathan Smith",
		contact: "+1 (555) 012-3456",
		assignedVehicle: "TX-452-901",
		licenseExpiry: "Oct 12, 2025",
		licenseExpiryDetail: "Valid for 18mo",
		isLicenseOverdue: false,
		status: "Assigned",
		trips: "1,248",
		rating: "4.9",
	},
	{
		id: "drv-2",
		driverId: "DRV-4482",
		name: "Michael Rodriguez",
		contact: "+1 (555) 987-6543",
		assignedVehicle: "CA-881-229",
		licenseExpiry: "Dec 15, 2023",
		licenseExpiryDetail: "Expires in 12 days",
		isLicenseOverdue: true,
		status: "Assigned",
		trips: "850",
		rating: "4.7",
	},
	{
		id: "drv-3",
		driverId: "DRV-1102",
		name: "Sarah Jenkins",
		contact: "+1 (555) 234-5678",
		assignedVehicle: "Unassigned",
		licenseExpiry: "Mar 30, 2026",
		licenseExpiryDetail: "Valid for 2y+",
		isLicenseOverdue: false,
		status: "Available",
		trips: "312",
		rating: "5.0",
	},
	{
		id: "drv-4",
		driverId: "DRV-7761",
		name: "Robert Chen",
		contact: "+1 (555) 345-6789",
		assignedVehicle: "Unassigned",
		licenseExpiry: "Jan 18, 2025",
		licenseExpiryDetail: "Valid for 13mo",
		isLicenseOverdue: false,
		status: "Leave",
		trips: "2,561",
		rating: "4.6",
	},
	{
		id: "drv-5",
		driverId: "DRV-3390",
		name: "Aisha Patel",
		contact: "+91 98765 43210",
		assignedVehicle: "MH-12-FR-4592",
		licenseExpiry: "Aug 22, 2025",
		licenseExpiryDetail: "Valid for 20mo",
		isLicenseOverdue: false,
		status: "Assigned",
		trips: "987",
		rating: "4.8",
	},
	{
		id: "drv-6",
		driverId: "DRV-5512",
		name: "Rajesh Kumar",
		contact: "+91 91234 56789",
		assignedVehicle: "KA-51-MM-0092",
		licenseExpiry: "Feb 10, 2024",
		licenseExpiryDetail: "Expires in 8 days",
		isLicenseOverdue: true,
		status: "Assigned",
		trips: "1,540",
		rating: "4.5",
	},
	{
		id: "drv-7",
		driverId: "DRV-8821",
		name: "Suresh Murali",
		contact: "+91 88901 23456",
		assignedVehicle: "Unassigned",
		licenseExpiry: "Jun 30, 2026",
		licenseExpiryDetail: "Valid for 2y+",
		isLicenseOverdue: false,
		status: "Available",
		trips: "420",
		rating: "4.9",
	},
	{
		id: "drv-8",
		driverId: "DRV-2204",
		name: "Priya Sharma",
		contact: "+91 97654 32109",
		assignedVehicle: "DL-01-AX-1022",
		licenseExpiry: "Nov 05, 2024",
		licenseExpiryDetail: "Valid for 11mo",
		isLicenseOverdue: false,
		status: "Assigned",
		trips: "765",
		rating: "4.7",
	},
	{
		id: "drv-9",
		driverId: "DRV-6634",
		name: "Amit Singh",
		contact: "+91 93456 78901",
		assignedVehicle: "Unassigned",
		licenseExpiry: "Sep 18, 2025",
		licenseExpiryDetail: "Valid for 21mo",
		isLicenseOverdue: false,
		status: "Leave",
		trips: "1,102",
		rating: "4.3",
	},
	{
		id: "drv-10",
		driverId: "DRV-4471",
		name: "David Kim",
		contact: "+1 (555) 678-9012",
		assignedVehicle: "TX-334-882",
		licenseExpiry: "Jan 25, 2024",
		licenseExpiryDetail: "Expires in 5 days",
		isLicenseOverdue: true,
		status: "Assigned",
		trips: "2,890",
		rating: "4.6",
	},
	{
		id: "drv-11",
		driverId: "DRV-9903",
		name: "Emma Stone",
		contact: "+44 7911 234567",
		assignedVehicle: "Unassigned",
		licenseExpiry: "May 12, 2027",
		licenseExpiryDetail: "Valid for 3y+",
		isLicenseOverdue: false,
		status: "Available",
		trips: "634",
		rating: "5.0",
	},
	{
		id: "drv-12",
		driverId: "DRV-1188",
		name: "Marcus Chen",
		contact: "+1 (555) 321-0987",
		assignedVehicle: "CA-991-447",
		licenseExpiry: "Mar 08, 2025",
		licenseExpiryDetail: "Valid for 14mo",
		isLicenseOverdue: false,
		status: "Assigned",
		trips: "1,876",
		rating: "4.8",
	},
];
