import { createSlice } from "@reduxjs/toolkit";
import { ReportsState } from "../../types/reports";

const initialState: ReportsState = {
	stats: {
		totalShipment: { title: 'Total Shipment', value: '1,284', change: '+12%', changeType: 'increase', icon: 'ship' },
		clearances: { title: 'Clearances', value: '942', change: '+8%', changeType: 'increase', icon: 'clock' },
		pending: { title: 'Pending', value: '56', change: '0%', changeType: 'neutral', icon: 'file' },
		delayed: { title: 'Delayed', value: '18', change: '+5%', changeType: 'increase', icon: 'alert' },
		revenue: { title: 'Revenue', value: '₹4.2M', change: '+24%', changeType: 'increase', icon: 'money' },
		activeAlerts: { title: 'Active Alerts', value: '₹3.2M', change: '-15%', changeType: 'decrease', icon: 'exclamation' },
	},
	trends: [
		{ day: 'Mon', thisMonth: 60, lastMonth: 40 },
		{ day: 'Tue', thisMonth: 80, lastMonth: 50 },
		{ day: 'Wed', thisMonth: 65, lastMonth: 45 },
		{ day: 'Thu', thisMonth: 100, lastMonth: 70 },
		{ day: 'Fri', thisMonth: 55, lastMonth: 40 },
		{ day: 'Sat', thisMonth: 35, lastMonth: 25 },
	],
	clearanceStatus: [
		{ name: 'Completed', value: 75, color: '#004BCA' },
		{ name: 'Processing', value: 15, color: '#006972' },
		{ name: 'Pending', value: 10, color: '#BA1A1A' },
	],
	revVsCost: {
		netRevenue: 284000,
		operationCost: 128500,
		efficiencyNote: 'Efficiency is up by 4.2% compared to Q3.'
	},
	monthlyVolume: [
		{ month: 'May', volume: 30 },
		{ month: 'Jun', volume: 55 },
		{ month: 'Jul', volume: 48 },
		{ month: 'Aug', volume: 68 },
		{ month: 'Sep', volume: 92 },
		{ month: 'Sep', volume: 60 } // Keeping visual match with user's duplicate Sep label
	],
	allShipments: [
		{ id: '#AG-84920', customer: 'Quantum Dynamics Inc.', route: 'Berlin, Germany', subRoute: 'Hub-North Logistics', type: 'Export', status: 'IN Transit', date: 'Oct 24, 2023' },
		{ id: '#AG-84921', customer: 'Swift Auto Parts', route: 'Shanghai, CN', subRoute: 'Los Angeles, US', type: 'Import', status: 'Processing', date: 'Oct 26, 2023' },
		{ id: '#AG-84925', customer: 'Global Bio-Medical', route: 'Busan, KR', subRoute: 'Rotterdam, NL', type: 'Import', status: 'IN Transit', date: 'Oct 22, 2023' },
		{ id: '#AG-84921', customer: 'Swift Auto Parts', route: 'Tokyo, JP', subRoute: 'Sydney, AU', type: 'Export', status: 'Processing', date: 'Oct 26, 2023' },
		{ id: '#AG-84925', customer: 'Global Bio-Medical', route: 'Busan, KR', subRoute: 'Rotterdam, NL', type: 'Import', status: 'Alert', date: 'Oct 22, 2023' },
		{ id: '#AG-84921', customer: 'Swift Auto Parts', route: 'Berlin, DE', subRoute: 'New York, US', type: 'Export', status: 'Processing', date: 'Oct 26, 2023' },
		{ id: '#AG-84925', customer: 'Global Bio-Medical', route: 'Busan, KR', subRoute: 'Rotterdam, NL', type: 'Import', status: 'IN Transit', date: 'Oct 22, 2023' }
	],
	intelligenceInsights: [
		{
			id: 'insight-1',
			title: 'Delays increased 15%',
			description: 'Heavy congestion at the Maritime Hub is affecting 48-hour delivery windows. Suggest rerouting urgent cargo to Air Hub B.'
		},
		{
			id: 'insight-2',
			title: 'Cost Optimization Opportunity',
			description: 'Consolidating LTL shipments on the Chicago-NY route could save $14,200 this week.'
		},
		{
			id: 'insight-3',
			title: 'Predicted Peak',
			description: 'Incoming volume expected to rise 22% next Tuesday due to seasonal spikes. Scale workforce at Bay 4.'
		}
	],
	activityTimeline: [
		{
			id: 'timeline-1',
			type: 'success',
			title: 'Shipment Delivered: #AG-88220',
			description: 'Confirmed at 15:42 by Driver: Michael J. (Bay Area Hub)'
		},
		{
			id: 'timeline-2',
			type: 'info',
			title: 'System Export: Financial Quarter Report',
			description: 'Generated by Admin Sarah L. for Executive Review.'
		},
		{
			id: 'timeline-3',
			type: 'warning',
			title: 'Delayed Alert: Customs Discrepancy',
			description: 'Shipment #AG-90215 flagged for manual inspection at Terminal 4.'
		},
		{
			id: 'timeline-4',
			type: 'warning',
			title: 'Delayed Alert: Customs Discrepancy',
			description: 'Shipment #AG-90215 flagged for manual inspection at Terminal 4.'
		},
		{
			id: 'timeline-5',
			type: 'warning',
			title: 'Delayed Alert: Customs Discrepancy',
			description: 'Shipment #AG-90215 flagged for manual inspection at Terminal 4.'
		}
	]
};

export const reportsSlice = createSlice({
	name: "reports",
	initialState,
	reducers: {},
});

export default reportsSlice.reducer;
