import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { TrackingStats, TrackingJob, TrackingNotification } from '../../types/tracking';

interface TrackingState {
  stats: TrackingStats;
  jobs: TrackingJob[];
  notifications: TrackingNotification[];
}

const initialState: TrackingState = {
  stats: {
    activeShipments: { count: 142, change: '+12%' },
    onTimeDelivery: { percentage: 94.8, change: '-12%' },
    customersPending: { count: 18, change: '+4%' },
    criticalAlerts: { count: 3, change: '-2%' }
  },
  notifications: [
    { id: '1', type: 'Critical Delay', message: 'Vessel TRK-8834 delayed at port.', severity: 'error' },
    { id: '2', type: 'Customers Hold', message: 'TRK-9021 requires additional document.', severity: 'warning' },
    { id: '3', type: 'Reroute Alert', message: 'Severe weather on hamburg -> BOS route.', severity: 'error' }
  ],
  jobs: [
    {
      id: 'JB-44092',
      customerId: 'TRK-9021',
      customerName: 'Global Tech Industries',
      status: 'In Transit',
      routeOrigin: 'Shanghai',
      routeDestination: 'Lax',
      eta: 'Oct 14, 2023',
      type: 'Export',
      details: {
        origin: 'Shanghai, CN',
        originSub: 'Terminal 4S',
        destination: 'Rotterdam, NL',
        destinationSub: 'ECT Delta',
        containers: '2 x 40 HC',
        containersSub: 'High Cube',
        carrier: 'Evergreen',
        carrierSub: 'Vessel: Ever Glory',
        currentPosition: 'Nort Sea',
        currentPositionSub: 'Approaching Port',
        timeline: [
          { title: 'Job Created', date: 'Oct 10, 09:12 AM', subtitle: 'System generated by @ops_lead', status: 'completed' },
          { title: 'Picked Up', date: 'Oct 12, 14:45 PM', subtitle: 'Terminal 4S, Shanghai, CN • Updated by Ground Team', status: 'completed' },
          { 
            title: 'In Transit - Sea Voyage', 
            date: 'Current Stage', 
            status: 'current',
            extraInfo: {
              description: 'Vessel EVER GLORY at North Sea. Estimated arrival at Rotterdam anchorage within 12 hours.',
              speed: '18.4 kn',
              heading: '245° SW'
            }
          },
          { title: 'Arrived at Port', date: 'Exp: Oct 26, 02:00 AM', subtitle: 'ECT Delta Terminal, Rotterdam, NL', status: 'pending' },
          { title: 'Customs Cleared', date: 'Exp: Oct 27, 10:00 AM', status: 'pending' },
          { title: 'Delivered', date: 'Exp: Oct 28, 17:00 PM', status: 'pending' }
        ],
        pendingActions: [
          { title: 'Confirm ETA', subtitle: 'Due in 4 hours', status: 'Update' },
          { title: 'Notify Customer', subtitle: 'Waiting for berthing confirm', status: 'Pending' },
          { title: 'Confirm ETA', subtitle: 'Due in 4 hours', status: 'Update' },
          { title: 'Notify Customer', subtitle: 'Waiting for berthing confirm', status: 'Pending' }
        ],
        internalNotes: [
          { text: 'Transport Team confirm vessel berthing window. The North Sea congestion might push back port entry by 2 hours.', author: '@Marcus Sterling' },
          { text: 'Acknowledged Marcus. Monitoring ETA updates. Customer has been notified of potential 2hr delta.', author: '@Janice Doe' },
          { text: 'Berthing confirmed at Terminal ECT Delta, Slot A4. No change to final delivery ETA.', author: '@Transport Team' }
        ],
        activityLogs: [
          { title: "Status updated to 'In Transit'", date: 'Today, 09:15 AM · System Automator' },
          { title: "Document 'Commercial Invoice' verified", date: 'Yesterday, 04:30 PM · Sarah (FFT)' },
          { title: 'New note: "Customer requested expedited delivery."', date: 'Oct 22, 11:10 AM · Alex Chen' },
          { title: 'Job Created', date: 'Oct 12, 14:20' }
        ]
      }
    },
    { id: '1', customerId: 'TRK-9021', customerName: 'Global Imports LLC', status: 'In Transit', routeOrigin: 'Shanghai', routeDestination: 'Lax', eta: 'Oct 14, 2023' },
    { id: '2', customerId: 'TRK-8834', customerName: 'Nexus Electronics', status: 'Delayed', routeOrigin: 'Shenzhen', routeDestination: 'JFK', eta: 'Oct 18, 2023' },
    { id: '3', customerId: 'TRK-9112', customerName: 'Apex Manufacturing', status: 'At Port', routeOrigin: 'Rotterdam', routeDestination: 'NYC', eta: 'Oct 10, 2023' },
    { id: '4', customerId: 'TRK-7745', customerName: 'Sunrise Logistics', status: 'Cleared', routeOrigin: 'Miami', routeDestination: 'Bogota', eta: 'Oct 08, 2023' },
    { id: '5', customerId: 'TRK-8099', customerName: 'Velocity Goods', status: 'In Transit', routeOrigin: 'Hamburg', routeDestination: 'BOS', eta: 'Oct 22, 2023' },
    { id: '6', customerId: 'TRK-6610', customerName: 'Pacific Freight Co.', status: 'In Customs', routeOrigin: 'Tokyo', routeDestination: 'LAX', eta: 'Oct 11, 2023' },
    { id: '7', customerId: 'TRK-5503', customerName: 'Euro Trade Gmbh', status: 'Cleared', routeOrigin: 'Frankfurt', routeDestination: 'ORD', eta: 'Oct 5, 2023' },
    { id: '8', customerId: 'TRK-4482', customerName: 'Meridian Exports', status: 'Delayed', routeOrigin: 'Mumbai', routeDestination: 'DXB', eta: 'Oct 9, 2023' },
    { id: '9', customerId: 'TRK-3371', customerName: 'Atlas Supply Chain', status: 'At Port', routeOrigin: 'Singapore', routeDestination: 'LHR', eta: 'Oct 28, 2023' },
    { id: '10', customerId: 'TRK-2259', customerName: 'Nordic Cargo AS', status: 'At Port', routeOrigin: 'Oslo', routeDestination: 'SEA', eta: 'Oct 13, 2023' }
  ]
};

const trackingSlice = createSlice({
  name: 'tracking',
  initialState,
  reducers: {}
});

export default trackingSlice.reducer;
