import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { ShipmentJob, ShipmentJobDetails } from "../../types/transportation";

interface TransportationState {
  jobs: ShipmentJob[];
  searchQuery: string;
  activeTab: string;
}

const dummyDetails: ShipmentJobDetails = {
  destination: "Rotterdam",
  destinationCode: "NLRTM",
  originCode: "CNSHA",
  freightType: "Ocean",
  containerCount: "2 × 40' HC",
  bookingRef: "EVG-2020-K1",
  incoterms: "FOB",
  shipper: "Zhejiang Mfg Hub",
  consignee: "Global Dist. Center",
  vendorName: "EuroTrans",
  vendorPhone: "+31 6 1234 5678",
  coordinator: "Elena Vance",
  routePlanOrigin: "Rotterdam Port",
  routePlanDestination: "Dist. Center B",
  containers: [
    { type: "40' High Cube", quantity: 2, grossWeight: "22,400 Kg", volume: "134.00", hsCodes: "8517.12.00" },
    { type: "20' Standard", quantity: 1, grossWeight: "11,200 Kg", volume: "33.20", hsCodes: "8517.12.00" },
    { type: "40' Standard", quantity: 3, grossWeight: "27,600 Kg", volume: "102.40", hsCodes: "8504.40.90" },
  ],
  internalNotes: [
    { text: "Customer requested a 5% volume discount if they confirm by Friday.", author: "Sales Team", time: "2 hours ago" },
    { text: "Customer requested a 4% volume discount if they confirm by Friday.", author: "Sales Team", time: "3 hours ago" },
  ],
  activityLogs: [
    { title: "Status updated to 'In Transit'", subtitle: "Today, 09:15 AM - System Automator" },
    { title: "Document 'Commercial Invoice' verified", subtitle: "Yesterday, 04:30 PM - Sarah (FFT)" },
    { title: "New note: \"Customer requested expedited delivery.\"", subtitle: "Oct 22, 11:10 AM - Alex Chen" },
    { title: "Job Created", subtitle: "Oct 12, 14:20" },
  ],
  documents: [
    { name: "Bill of Lading (Master)", date: "—", type: "pdf" },
    { name: "Commercial Invoice", date: "Oct 11, 2024", type: "pdf-success" },
    { name: "Packing List", date: "Oct 11, 2024", type: "pdf-success" },
    { name: "Customs Entry 7501", date: "Oct 11, 2024", type: "pdf-success" },
  ],
  expenses: [
    { name: "Port handling Fee", amount: "₹3,205.00", status: "Confirmed" },
    { name: "Customs Clearance", amount: "₹3,250.00", status: "Pending" },
    { name: "Insurance Premium", amount: "₹3,260.00", status: "Confirmed" },
  ],
  insurancePolicyNumber: "Policy #INS-6692",
  insuranceCoverage: "All Risk — $850,000",
  insuranceExpiry: "3 Days Pre-Arrival",
  totalExpenses: "₹9,705.00",
};

const dummyJobs: ShipmentJob[] = [
  {
    id: "1",
    jobId: "#JOB-8842",
    customer: "Global Nexus Corp.",
    type: "Export",
    origin: "MUM",
    dropOff: "HAM",
    driverName: "Mark J.",
    vehicleNo: "KA01AB4587",
    status: "In Transit",
    scheduledTimeRange: "14:00 - 16:00",
    scheduledSubText: "",
    pickupDateTime: "18 Jun 2026, 09:30 AM",
    pickupPort: "Chennai Port",
    etaDate: "Oct 24, 2023",
    etaStatus: "On Schedule",
    impact: "CRITICAL",
    delayReason: "Weather (Force Majeure)",
    outForDeliveryRouteOrigin: "MUM -> HAM",
    outForDeliveryRouteDrop: "MUM -> HAM",
    outForDeliveryEta: "14:30 Today",
    deliveryDate: "2023-10-24",
    performance: "ON-TIME",
    pod: "14:30 Today",
    details: dummyDetails
  },
  {
    id: "2",
    jobId: "#JOB-8841",
    customer: "Next Logistics",
    type: "Import",
    origin: "SFO",
    dropOff: "LHR",
    driverName: "Sarah K.",
    vehicleNo: "KA03TR7821",
    status: "Delayed",
    scheduledTimeRange: "16:30 - 18:30",
    scheduledSubText: "",
    pickupDateTime: "18 Jun 2026, 11:00 AM",
    pickupPort: "JNPT Port",
    etaDate: "Oct 24, 2023",
    etaStatus: "Weather Delay",
    impact: "MAJOR",
    delayReason: "Port Congestion",
    outForDeliveryRouteOrigin: "SFO -> LHR",
    outForDeliveryRouteDrop: "SFO -> LHR",
    outForDeliveryEta: "15:15 Today",
    deliveryDate: "2023-10-24",
    performance: "EARLY",
    pod: "15:15 Today",
    details: dummyDetails
  },
  {
    id: "3",
    jobId: "#JOB-8842",
    customer: "Swift Mart",
    type: "Import",
    origin: "JFK",
    dropOff: "CDG",
    driverName: "MAN TGX",
    vehicleNo: "TN09DP5623",
    status: "Completed",
    scheduledTimeRange: "09:00 - 11:00",
    scheduledSubText: "(Tomorrow)",
    pickupDateTime: "19 Jun 2026, 08:00 AM",
    pickupPort: "Chennai Port",
    etaDate: "Oct 21, 2023",
    etaStatus: "Delivered",
    impact: "CRITICAL",
    delayReason: "Vehicle Maintenance",
    outForDeliveryRouteOrigin: "JFK -> CDG",
    outForDeliveryRouteDrop: "JFK -> CDG",
    outForDeliveryEta: "16:00 Today",
    deliveryDate: "2023-10-23",
    performance: "DELAYED",
    pod: "16:00 Today",
    details: dummyDetails
  },
  {
    id: "4",
    jobId: "#JOB-8841",
    customer: "Arctic Chill Co",
    type: "Export",
    origin: "SIN",
    dropOff: "SEA",
    driverName: "Oliver M.",
    vehicleNo: "MH12CT8841",
    status: "Out For Delivery",
    scheduledTimeRange: "11:00 - 13:00",
    scheduledSubText: "",
    pickupDateTime: "19 Jun 2026, 07:30 AM",
    pickupPort: "Mundra Port",
    etaDate: "Oct 24, 2023",
    etaStatus: "On Schedule",
    impact: "MODERATE",
    delayReason: "Customs Hold",
    outForDeliveryRouteOrigin: "SIN -> SEA",
    outForDeliveryRouteDrop: "SIN -> SEA",
    outForDeliveryEta: "14:45 Today",
    deliveryDate: "2023-10-23",
    performance: "EARLY",
    pod: "14:45 Today",
    details: dummyDetails
  },
  {
    id: "5",
    jobId: "#JOB-8842",
    customer: "Global Nexus Corp.",
    type: "Export",
    origin: "MUM",
    dropOff: "HAM",
    driverName: "Mark J.",
    vehicleNo: "GJ05LP7789",
    status: "In Transit",
    scheduledTimeRange: "14:00 - 16:00",
    scheduledSubText: "",
    pickupDateTime: "20 Jun 2026, 10:00 AM",
    pickupPort: "JNPT Port",
    etaDate: "Oct 24, 2023",
    etaStatus: "On Schedule",
    impact: "CRITICAL",
    delayReason: "Route Obstruction",
    outForDeliveryRouteOrigin: "MUM -> HAM",
    outForDeliveryRouteDrop: "MUM -> HAM",
    outForDeliveryEta: "14:30 Today",
    deliveryDate: "2023-10-23",
    performance: "DELAYED",
    pod: "14:30 Today",
    details: dummyDetails
  },
  {
    id: "6",
    jobId: "#JOB-8841",
    customer: "Next Logistics",
    type: "Export",
    origin: "SFO",
    dropOff: "LHR",
    driverName: "Sarah K.",
    vehicleNo: "AP16TR4421",
    status: "Delayed",
    scheduledTimeRange: "16:30 - 18:30",
    scheduledSubText: "",
    pickupDateTime: "20 Jun 2026, 06:00 AM",
    pickupPort: "Chennai Port",
    etaDate: "Oct 24, 2023",
    etaStatus: "Weather Delay",
    impact: "MAJOR",
    delayReason: "Weather (Force Majeure)",
    outForDeliveryRouteOrigin: "SFO -> LHR",
    outForDeliveryRouteDrop: "SFO -> LHR",
    outForDeliveryEta: "15:15 Today",
    deliveryDate: "2023-10-24",
    performance: "ON-TIME",
    pod: "15:15 Today",
    details: dummyDetails
  },
  {
    id: "7",
    jobId: "#JOB-8842",
    customer: "Swift Mart",
    type: "Import",
    origin: "JFK",
    dropOff: "CDG",
    driverName: "MAN TGX",
    vehicleNo: "WB20PT9945",
    status: "Completed",
    scheduledTimeRange: "09:00 - 11:00",
    scheduledSubText: "(Tomorrow)",
    pickupDateTime: "21 Jun 2026, 09:00 AM",
    pickupPort: "Mundra Port",
    etaDate: "Oct 21, 2023",
    etaStatus: "Delivered",
    impact: "MAJOR",
    delayReason: "Vehicle Maintenance",
    outForDeliveryRouteOrigin: "JFK -> CDG",
    outForDeliveryRouteDrop: "JFK -> CDG",
    outForDeliveryEta: "16:00 Today",
    deliveryDate: "2023-10-23",
    performance: "DELAYED",
    pod: "16:00 Today",
    details: dummyDetails
  },
  {
    id: "8",
    jobId: "#JOB-8841",
    customer: "Arctic Chill Co",
    type: "Export",
    origin: "SIN",
    dropOff: "SEA",
    driverName: "Oliver M.",
    vehicleNo: "DL01CP5567",
    status: "Out For Delivery",
    scheduledTimeRange: "11:00 - 13:00",
    scheduledSubText: "",
    pickupDateTime: "21 Jun 2026, 01:00 PM",
    pickupPort: "Kolkata Port",
    etaDate: "Oct 24, 2023",
    etaStatus: "On Schedule",
    impact: "MODERATE",
    delayReason: "Customs Hold",
    outForDeliveryRouteOrigin: "SIN -> SEA",
    outForDeliveryRouteDrop: "SIN -> SEA",
    outForDeliveryEta: "14:45 Today",
    deliveryDate: "2023-10-24",
    performance: "ON-TIME",
    pod: "14:45 Today",
    details: dummyDetails
  },
];

const initialState: TransportationState = {
  jobs: dummyJobs,
  searchQuery: "",
  activeTab: "All Shipments",
};

export const transportationSlice = createSlice({
  name: "transportation",
  initialState,
  reducers: {
    setSearchQuery: (state, action: PayloadAction<string>) => {
      state.searchQuery = action.payload;
    },
    setActiveTab: (state, action: PayloadAction<string>) => {
      state.activeTab = action.payload;
    },
  },
});

export const { setSearchQuery, setActiveTab } = transportationSlice.actions;

export default transportationSlice.reducer;
