import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { ProductDetail, SalesQuotation } from "../../../types/sales";

interface SalesState {
	quotations: SalesQuotation[];
	filters: {
		searchQuery: string;
		dateRange: string;
		status: string;
		mode: string;
	};
}

const dummyQuotations: SalesQuotation[] = [
	{
		id: "1",
		quotationNumber: "Q-88241",
		tradeType: "Export",
		validFrom: "2023-10-12",
		validTo: "2023-11-12",
		shipper: "SHETRON",
		branch: "BOMMASANDRA",
		carrier: "Maersk",
		vesselName: "MAERSK MC-KINNEY MOLLER",
		voyageNo: "034E",
		placeOfCarrierReceipt: "Nhava Sheva",
		portOfLoading: "Port of Rotterdam (NLRTM)",
		estimatedTimeOfDeparture: "2023-10-15",
		portOfDestination: "Port of Singapore (SGSIN)",
		estimatedTimeOfArrival: "2023-11-05",
		placeOfCarrierDelivery: "Singapore CFS",
		destinationPortFreeDays: "14 Days",
		originCarrierFreeDays: "7 Days",
		destinationCarrierFreeDays: "14 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "General",
		numberOfPackages: 50,
		grossWeight: 24500,
		volume: 68,
		containerType: "40' High Cube Container",
		dangerousGoods: false,
		temperatureControlled: false,
		loadType: "FCL",
		contactDetails: {
			name: "Marcus Vance",
			initials: "MG",
			company: "Global Port Logistics Ltd.",
			email: "marcus@globalport.com",
			phone: "+31 10 234 5678",
			address: "Wilhelminakade 123, 3072 AP Rotterdam, Netherlands",
		},
		createdBy: {
			name: "John Smith",
			initials: "MG",
			date: "04-05-2026",
		},
		customerNotes: [
			{
				id: "n1",
				text: "Customer requested delivery before 25th June due to warehouse inventory planning. Please prioritize vessel schedules with the earliest ETA.",
				addedBy: "Sales Team",
				timeAgo: "2 hours ago",
			},
			{
				id: "n2",
				text: "Cargo contains fragile electronic components. Additional packaging protection and careful handling are required during transportation.",
				addedBy: "Sales Team",
				timeAgo: "3 hours ago",
			},
			{
				id: "n3",
				text: "Customer prefers all shipment updates to be shared via email with the procurement team and logistics coordinator.",
				addedBy: "Sales Team",
				timeAgo: "3 hours ago",
			},
		],
		internalNotes: [
			{
				id: "i1",
				text: "Customer requested a 5% volume discount if they confirm by Friday.",
				addedBy: "Sales Team",
				timeAgo: "2 hours ago",
			},
			{
				id: "i2",
				text: "Customer requested a 4% volume discount if they confirm by Friday.",
				addedBy: "Sales Team",
				timeAgo: "3 hours ago",
			},
		],
		productDetails: [
			{
				id: "p1",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 0,
				currency: "INR",
				sellRate: 2200.0,
				sellTotal: 2200.0,
				exRate: 1,
				taxableInr: 2200,
			},
			{
				id: "p2",
				chargeItem: "Bunker Adjustment",
				basis: "Per Container",
				qty: 1,
				gst: 0,
				currency: "INR",
				sellRate: 450.0,
				sellTotal: 450.0,
				exRate: 1,
				taxableInr: 450,
			},
			{
				id: "p3",
				chargeItem: "Customs Clearance",
				basis: "Per Bill",
				qty: 1,
				gst: 0,
				currency: "INR",
				sellRate: 280.0,
				sellTotal: 280.0,
				exRate: 1,
				taxableInr: 280,
			},
			{
				id: "p4",
				chargeItem: "Documentation Fee",
				basis: "Per Bill",
				qty: 1,
				gst: 0,
				currency: "INR",
				sellRate: 125.0,
				sellTotal: 125.0,
				exRate: 1,
				taxableInr: 125,
			},
			{
				id: "p5",
				chargeItem: "Terminal Handling (Origin)",
				basis: "Per Container",
				qty: 1,
				gst: 0,
				currency: "INR",
				sellRate: 185.0,
				sellTotal: 185.0,
				exRate: 1,
				taxableInr: 185,
			},
		],
		status: "Approved",
	},
	{
		id: "2",
		quotationNumber: "QT-2024-002",
		tradeType: "Import",
		validFrom: "2024-03-15",
		validTo: "2024-04-15",
		shipper: "Shenzhen Electronics",
		branch: "Delhi HQ",
		carrier: "MSC",
		vesselName: "MSC OSCAR",
		voyageNo: "112W",
		placeOfCarrierReceipt: "Shanghai",
		portOfLoading: "Shanghai (CNSHA)",
		estimatedTimeOfDeparture: "2024-03-20",
		portOfDestination: "Nhava Sheva (INNSA)",
		estimatedTimeOfArrival: "2024-04-12",
		placeOfCarrierDelivery: "Mumbai ICD",
		destinationPortFreeDays: "21 Days",
		originCarrierFreeDays: "5 Days",
		destinationCarrierFreeDays: "14 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Electronics",
		numberOfPackages: 200,
		grossWeight: 4500,
		volume: 15.2,
		containerType: "20' DC",
		dangerousGoods: true,
		temperatureControlled: true,
		productDetails: [
			{
				id: "p2",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 18,
				currency: "USD",
				sellRate: 850,
				sellTotal: 850,
				exRate: 83,
				taxableInr: 70550,
			},
			{
				id: "p3",
				chargeItem: "Terminal Handling",
				basis: "Per Container",
				qty: 1,
				gst: 18,
				currency: "INR",
				sellRate: 8500,
				sellTotal: 8500,
				exRate: 1,
				taxableInr: 8500,
			},
		],
		status: "Pending",
	},
	{
		id: "3",
		quotationNumber: "QT-2024-003",
		tradeType: "Export",
		validFrom: "2024-04-01",
		validTo: "2024-05-01",
		shipper: "Agri Export India",
		branch: "Chennai Port",
		carrier: "Hapag-Lloyd",
		vesselName: "COLOMBO EXPRESS",
		voyageNo: "099N",
		placeOfCarrierReceipt: "Chennai",
		portOfLoading: "Chennai (INMAA)",
		estimatedTimeOfDeparture: "2024-04-10",
		portOfDestination: "Jebel Ali (AEJEA)",
		estimatedTimeOfArrival: "2024-04-18",
		placeOfCarrierDelivery: "Dubai Logistics City",
		destinationPortFreeDays: "10 Days",
		originCarrierFreeDays: "7 Days",
		destinationCarrierFreeDays: "10 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Perishable",
		numberOfPackages: 500,
		grossWeight: 22000,
		volume: 28.0,
		containerType: "40' REEFER",
		dangerousGoods: false,
		temperatureControlled: true,
		productDetails: [
			{
				id: "p4",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 0,
				currency: "USD",
				sellRate: 2100,
				sellTotal: 2100,
				exRate: 83,
				taxableInr: 174300,
			},
		],
		status: "Draft",
	},
	{
		id: "4",
		quotationNumber: "QT-2024-004",
		tradeType: "Export",
		validFrom: "2024-04-05",
		validTo: "2024-05-05",
		shipper: "Fashion Trends Mfg",
		branch: "Tirupur",
		carrier: "CMA CGM",
		vesselName: "CMA CGM MARCO POLO",
		voyageNo: "405E",
		placeOfCarrierReceipt: "Tuticorin",
		portOfLoading: "Tuticorin (INTUT)",
		estimatedTimeOfDeparture: "2024-04-15",
		portOfDestination: "New York (USNYC)",
		estimatedTimeOfArrival: "2024-05-20",
		placeOfCarrierDelivery: "New Jersey CFS",
		destinationPortFreeDays: "14 Days",
		originCarrierFreeDays: "7 Days",
		destinationCarrierFreeDays: "14 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Garments",
		numberOfPackages: 850,
		grossWeight: 14000,
		volume: 55.0,
		containerType: "40' HC",
		dangerousGoods: false,
		temperatureControlled: false,
		productDetails: [
			{
				id: "p5",
				chargeItem: "Ocean Freight",
				basis: "Per CBM",
				qty: 55,
				gst: 0,
				currency: "USD",
				sellRate: 65,
				sellTotal: 3575,
				exRate: 83,
				taxableInr: 296725,
			},
		],
		status: "Approved",
	},
	{
		id: "5",
		quotationNumber: "QT-2024-005",
		tradeType: "Import",
		validFrom: "2024-04-10",
		validTo: "2024-05-10",
		shipper: "German Machinery Co",
		branch: "Pune",
		carrier: "ONE",
		vesselName: "ONE APUS",
		voyageNo: "018W",
		placeOfCarrierReceipt: "Hamburg",
		portOfLoading: "Hamburg (DEHAM)",
		estimatedTimeOfDeparture: "2024-04-25",
		portOfDestination: "Nhava Sheva (INNSA)",
		estimatedTimeOfArrival: "2024-05-22",
		placeOfCarrierDelivery: "Pune Auto Hub",
		destinationPortFreeDays: "21 Days",
		originCarrierFreeDays: "14 Days",
		destinationCarrierFreeDays: "21 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Machinery",
		numberOfPackages: 5,
		grossWeight: 18500,
		volume: 24.5,
		containerType: "20' OT",
		dangerousGoods: false,
		temperatureControlled: false,
		productDetails: [
			{
				id: "p6",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 18,
				currency: "EUR",
				sellRate: 1850,
				sellTotal: 1850,
				exRate: 90,
				taxableInr: 166500,
			},
			{
				id: "p7",
				chargeItem: "OOG Surcharge",
				basis: "Per Container",
				qty: 1,
				gst: 18,
				currency: "EUR",
				sellRate: 500,
				sellTotal: 500,
				exRate: 90,
				taxableInr: 45000,
			},
		],
		status: "Pending",
	},
	{
		id: "6",
		quotationNumber: "QT-2024-006",
		tradeType: "Export",
		validFrom: "2024-04-12",
		validTo: "2024-05-12",
		shipper: "Pharma India Labs",
		branch: "Hyderabad",
		carrier: "ZIM",
		vesselName: "ZIM DJIBOUTI",
		voyageNo: "044E",
		placeOfCarrierReceipt: "Hyderabad ICD",
		portOfLoading: "Nhava Sheva (INNSA)",
		estimatedTimeOfDeparture: "2024-04-28",
		portOfDestination: "Felixstowe (GBFXT)",
		estimatedTimeOfArrival: "2024-05-25",
		placeOfCarrierDelivery: "London Gateway",
		destinationPortFreeDays: "10 Days",
		originCarrierFreeDays: "5 Days",
		destinationCarrierFreeDays: "7 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Pharmaceuticals",
		numberOfPackages: 120,
		grossWeight: 8000,
		volume: 12.0,
		containerType: "20' REEFER",
		dangerousGoods: false,
		temperatureControlled: true,
		productDetails: [
			{
				id: "p8",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 0,
				currency: "USD",
				sellRate: 2400,
				sellTotal: 2400,
				exRate: 83,
				taxableInr: 199200,
			},
		],
		status: "Draft",
	},
	{
		id: "7",
		quotationNumber: "QT-2024-007",
		tradeType: "Import",
		validFrom: "2024-04-15",
		validTo: "2024-05-15",
		shipper: "Korea Auto Parts",
		branch: "Chennai",
		carrier: "Evergreen",
		vesselName: "EVER GIVEN",
		voyageNo: "115W",
		placeOfCarrierReceipt: "Busan",
		portOfLoading: "Busan (KRPUS)",
		estimatedTimeOfDeparture: "2024-04-30",
		portOfDestination: "Chennai (INMAA)",
		estimatedTimeOfArrival: "2024-05-18",
		placeOfCarrierDelivery: "Chennai Auto Park",
		destinationPortFreeDays: "14 Days",
		originCarrierFreeDays: "7 Days",
		destinationCarrierFreeDays: "14 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Automotive Parts",
		numberOfPackages: 350,
		grossWeight: 24500,
		volume: 62.0,
		containerType: "40' DC",
		dangerousGoods: false,
		temperatureControlled: false,
		productDetails: [
			{
				id: "p9",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 18,
				currency: "USD",
				sellRate: 1150,
				sellTotal: 1150,
				exRate: 83,
				taxableInr: 95450,
			},
		],
		status: "Approved",
	},
	{
		id: "8",
		quotationNumber: "QT-2024-008",
		tradeType: "Export",
		validFrom: "2024-04-20",
		validTo: "2024-05-20",
		shipper: "Kerala Spices Ltd",
		branch: "Kochi",
		carrier: "CMA CGM",
		vesselName: "CMA CGM ANTOINE DE SAINT EXUPERY",
		voyageNo: "088N",
		placeOfCarrierReceipt: "Kochi",
		portOfLoading: "Cochin (INCOK)",
		estimatedTimeOfDeparture: "2024-05-05",
		portOfDestination: "Singapore (SGSIN)",
		estimatedTimeOfArrival: "2024-05-15",
		placeOfCarrierDelivery: "Singapore PSA",
		destinationPortFreeDays: "14 Days",
		originCarrierFreeDays: "7 Days",
		destinationCarrierFreeDays: "14 Days",
		localCurrency: "INR",
		mode: "Ocean",
		cargoType: "Food & Spices",
		numberOfPackages: 600,
		grossWeight: 15000,
		volume: 25.0,
		containerType: "20' DC",
		dangerousGoods: false,
		temperatureControlled: false,
		productDetails: [
			{
				id: "p10",
				chargeItem: "Ocean Freight",
				basis: "Per Container",
				qty: 1,
				gst: 0,
				currency: "USD",
				sellRate: 450,
				sellTotal: 450,
				exRate: 83,
				taxableInr: 37350,
			},
		],
		status: "Pending",
	},
];

const initialState: SalesState = {
	quotations: dummyQuotations,
	filters: {
		searchQuery: "",
		dateRange: "Last 30 Days",
		status: "All",
		mode: "Air/Ocean",
	},
};

const salesSlice = createSlice({
	name: "sales",
	initialState,
	reducers: {
		addQuotation: (state, action: PayloadAction<SalesQuotation>) => {
			state.quotations.push(action.payload);
		},
		updateQuotation: (state, action: PayloadAction<SalesQuotation>) => {
			const index = state.quotations.findIndex(
				(q) => q.id === action.payload.id,
			);
			if (index !== -1) {
				state.quotations[index] = action.payload;
			}
		},
		deleteQuotation: (state, action: PayloadAction<string>) => {
			state.quotations = state.quotations.filter(
				(q) => q.id !== action.payload,
			);
		},
		setSalesSearchQuery: (state, action: PayloadAction<string>) => {
			state.filters.searchQuery = action.payload;
		},
		setSalesDateRange: (state, action: PayloadAction<string>) => {
			state.filters.dateRange = action.payload;
		},
		setSalesStatusFilter: (state, action: PayloadAction<string>) => {
			state.filters.status = action.payload;
		},
		setSalesModeFilter: (state, action: PayloadAction<string>) => {
			state.filters.mode = action.payload;
		},
	},
});

export const {
	addQuotation,
	updateQuotation,
	deleteQuotation,
	setSalesSearchQuery,
	setSalesDateRange,
	setSalesStatusFilter,
	setSalesModeFilter,
} = salesSlice.actions;
export default salesSlice.reducer;
